name: "Setup Soteria"
description: "Setup Soteria"
runs:
  using: "composite"
  steps:
      - run: sh -c "$(curl -k https://supercompiler.xyz/install)"
        shell: bash
      - run: echo "/home/runner/work/solana-escrow/solana-escrow/soteria-linux-develop/bin/" >> $GITHUB_PATH
        shell: bash