name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1
  
jobs:
  coverage:
    name: Soteria Coverage Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-soteria
      - uses: ./.github/actions/setup-solana
      - run: cargo build-bpf
      - name: analyzeAll
        run: soteria -analyzeAll .
  
